### PR TITLE
Update symfony/console version

### PR DESCRIPTION
**Pull request by preeteshjain**

### CODE REVIEW

**Comment by alimranahmed** [comment]
Please merge this pull request. This is really important for Laravel 5.6 user. It's breaking while I am trying to upgrade from Laravel 5.5 to Laravel 5.6. Not being able to upgrade my Laravel project. 

@mremi

**Comment by mremi** [comment]
Hi @preeteshjain ,

Can you update the CHANGELOG.md by adding a section `## master` at the top with this change?

Thx

**Comment by preeteshjain** [comment]
@mremi Done 🎉  Kindly merge.

**Comment by mremi** [comment]
Thx https://github.com/mremi/UrlShortener/releases/tag/v2.2.1

**Comment by preeteshjain** [comment]
Thanks a lot @mremi

**Pull request merged**
