### PR TITLE
Update to Bitly API v4

### PR DESCRIPTION
**Pull request by mcaskill**
This is an amalgamation of PR #22 and the [requested changes](https://github.com/mremi/UrlShortener/pull/22/files/e7258373e1ea86c9833def54a46ea7595dffbea4) to syntax and updates to unit tests.

The `.travis.yml` file is also updated to fix issues with PHP 5.5 and HHVM.

### CODE REVIEW

**Comment by mcaskill** [comment]
Not sure what to do about Travis with [PHP 5.5](https://travis-ci.org/mremi/UrlShortener/jobs/660702541) and [HHVM](https://travis-ci.org/mremi/UrlShortener/jobs/660702545).

**Comment by mcaskill** [comment]
@mremi

Sorry for the delay in fixing PHP 5.5/HHVM; I am not well versed with Travis or HHVM.

Hopefully, we can get this request merged and tagged soon.

Thanks

**Comment by azine** [comment]
Hope to see Bitly V4 supported as well a.s.a.p. as bitly shuts down v3 in one week! => by 31st March 2020!

@mcaskill thanks for your work!

**Comment by mremi** [comment]
Could you please rebase to fix conflicts?

**Comment by mcaskill** [comment]
Thanks @mremi! Much appreciated.

**Comment by mremi** [comment]
Thanks a lot @mcaskill 👍

**Comment by mcaskill** [comment]
@mremi If you are looking for a quick changelog for the tagging (unsure if you want to do 2.3.0 or 2.2.2): https://github.com/mcaskill/UrlShortener/compare/b309ae90...e961c428

**Comment by mremi** [comment]
Thanks, I've just created https://github.com/mremi/UrlShortener/releases/tag/v2.3.0

**Comment by mcaskill** [comment]
Thank you! I hope you're staying safe in these difficult times.

**Comment by mremi** [comment]
Yes we have to, hope you too! Take care

**Pull request merged**
