### PR TITLE
Replace deprecated guzzle/guzzle with guzzlehttp/guzzle

### LINKED ISSUE #5: Depricated guzzle/guzzle
https://packagist.org/packages/guzzle/guzzle is depricated in favour of https://packagist.org/packages/guzzlehttp/guzzle, any chance this will get updated soon?

### PR DESCRIPTION
**Pull request by StudioMaX**
I have also bumped minimum required PHP version to 5.5, because this is minimum supported version for guzzlehttp/guzzle.

Fixes #5

### CODE REVIEW

**Comment by StudioMaX** [comment]
Maybe we could release this version as v1.1.0 or even v2.0.0?

**Comment by mremi** [comment]
Nice job @StudioMaX , thx, still WIP?

**Comment by mremi** [comment]
Can you add a `CHANGELOG.md` file plz and squash your commits?

**Comment by StudioMaX** [comment]
I've added a changelog.
Because we removed the `guzzle/guzzle` dependency this version won't be BC with 1.0.x. Which version you want to choice?

**Comment by mremi** [comment]
I think 2.0.0 is the best choice, because of php + guzzle upgrades

**Comment by mremi** [comment]
Thanks @StudioMaX 👍

**Pull request merged**
